export const dynamic = 'force-dynamic';

import { NextRequest, NextResponse } from 'next/server';
import { createAdminClient } from '@/lib/supabase/server';
import { requireManagementUser, unauthorizedResponse } from '@/lib/auth/requireAuthorizedUser';
import { isServiceEnabled, logServiceRun } from '@/lib/system-services';
import { logActivity, userActor } from '@/lib/activity-log';
import { randomBytes } from 'crypto';

// ─── helpers ──────────────────────────────────────────────────────────────────

function buildOrigin(req: NextRequest): string {
  return req.headers.get('origin') || process.env.NEXT_PUBLIC_APP_URL || '';
}

// Courier WhatsApp message. Deliberately impersonal — no "היי", no courier
// name, no recipient details inline. The link is the courier's full view
// of the delivery (recipient, phone, address, items, notes, mark-delivered
// button). Keeping the WhatsApp body short avoids leaking customer info
// into the courier's chat history and makes the link the only action.
//
// `courierName / recipientName / address / recipientPhone` are intentionally
// no longer part of the message body; the parameters are kept on the
// signature for back-compat with existing call sites and are unused here.
function buildWaUrl(
  phone: string,
  _courierName: string,
  _recipientName: string,
  _address: string | null,
  _recipientPhone: string | null,
  link: string,
): string {
  let p = phone.replace(/[^0-9]/g, '');
  if (p.startsWith('0')) p = '972' + p.slice(1);
  const lines = [
    'משלוח חדש מעדי תכשיט שוקולד',
    '',
    'לצפייה בפרטי המשלוח וההזמנה ולסימון מסירה:',
    link,
    '',
    'יש לפתוח את הקישור כדי לראות שם מקבל, כתובת, טלפון, הערות ופרטי הזמנה.',
  ];
  return `https://wa.me/${p}?text=${encodeURIComponent(lines.join('\n'))}`;
}

// ─── PATCH ────────────────────────────────────────────────────────────────────

export async function PATCH(req: NextRequest, { params }: { params: { id: string } }) {
  const auth = await requireManagementUser();
  if (!auth) return unauthorizedResponse();
  const supabase = createAdminClient();
  const body = await req.json();

  // ── Auto-create delivery record for synthetic no-record IDs ───────────────
  // Synthetic IDs look like 'no-record-{orderId}' and are generated by the
  // GET handler for orders that qualify as deliveries but have no record yet.
  let deliveryId = params.id;
  let wasCreated = false;

  if (deliveryId.startsWith('no-record-')) {
    const orderId = deliveryId.replace('no-record-', '');
    console.log('[delivery PATCH] synthetic id — orderId:', orderId);

    // Race-condition guard: check if a delivery was already created for this order
    const { data: existing } = await supabase
      .from('משלוחים')
      .select('id')
      .eq('הזמנה_id', orderId)
      .maybeSingle();

    if (existing) {
      deliveryId = existing.id;
      console.log('[delivery PATCH] delivery already existed, using id:', deliveryId);
    } else {
      const { data: order, error: orderErr } = await supabase
        .from('הזמנות')
        .select('id, תאריך_אספקה, שעת_אספקה, כתובת_מקבל_ההזמנה, עיר, הוראות_משלוח')
        .eq('id', orderId)
        .single();

      if (orderErr || !order) {
        console.error('[delivery PATCH] order not found:', orderId);
        return NextResponse.json({ error: 'הזמנה לא נמצאה' }, { status: 404 });
      }

      const { data: created, error: createErr } = await supabase
        .from('משלוחים')
        .insert({
          הזמנה_id:      orderId,
          סטטוס_משלוח:   'ממתין',
          תאריך_משלוח:   order.תאריך_אספקה  ?? null,
          שעת_משלוח:     order.שעת_אספקה    ?? null,
          כתובת:          order.כתובת_מקבל_ההזמנה ?? null,
          עיר:             order.עיר          ?? null,
          הוראות_משלוח:   order.הוראות_משלוח ?? null,
        })
        .select('id')
        .single();

      if (createErr || !created) {
        console.error('[delivery PATCH] auto-create failed:', createErr?.message);
        return NextResponse.json({ error: createErr?.message || 'שגיאה ביצירת משלוח' }, { status: 500 });
      }

      deliveryId = created.id;
      wasCreated = true;
      console.log('[delivery PATCH] auto-created delivery, new id:', deliveryId);
    }
  }

  const newStatus: string | undefined = body.סטטוס_משלוח;

  // ── Plain update (not a status→נאסף transition) ──────────────────────────
  if (newStatus !== 'נאסף') {
    // Capture pre-state for the activity log so old/new values are accurate.
    const { data: pre } = await supabase
      .from('משלוחים')
      .select('סטטוס_משלוח, courier_id')
      .eq('id', deliveryId)
      .maybeSingle();
    const { data, error } = await supabase
      .from('משלוחים')
      .update(body)
      .eq('id', deliveryId)
      .select()
      .single();
    if (error) return NextResponse.json({ error: error.message }, { status: 500 });
    // Log status changes (e.g. operator marking 'נמסר' from the desk).
    if (newStatus && pre && newStatus !== pre.סטטוס_משלוח) {
      void logActivity({
        actor:       userActor(auth),
        module:      'deliveries',
        action:      'delivery_status_changed',
        status:      'success',
        entityType:  'delivery',
        entityId:    deliveryId,
        title:       `שינוי סטטוס משלוח: ${pre.סטטוס_משלוח ?? '—'} → ${newStatus}`,
        oldValue:    { סטטוס_משלוח: pre.סטטוס_משלוח },
        newValue:    { סטטוס_משלוח: newStatus },
        request:     req,
      });
    }
    // Log courier assignment as a separate event when one was set/changed.
    if (body.courier_id && body.courier_id !== (pre?.courier_id ?? null)) {
      void logActivity({
        actor:       userActor(auth),
        module:      'deliveries',
        action:      'delivery_courier_assigned',
        status:      'success',
        entityType:  'delivery',
        entityId:    deliveryId,
        title:       'שליח שויך למשלוח',
        oldValue:    { courier_id: pre?.courier_id ?? null },
        newValue:    { courier_id: body.courier_id },
        request:     req,
      });
    }
    return NextResponse.json({ data, was_created: wasCreated });
  }

  // ── Status changing to נאסף — run auto-send trigger ───────────────────────
  console.log('[delivery PATCH] status → נאסף, delivery id:', deliveryId);

  // 1. Fetch current delivery + courier + order
  // Use * on courier join so missing columns (e.g. אימייל_שליח before migration 008) don't break the query
  const { data: existing, error: fetchErr } = await supabase
    .from('משלוחים')
    .select(`
      id, סטטוס_משלוח, delivery_token,
      courier_id, whatsapp_sent_at, email_sent_at,
      כתובת, עיר,
      הזמנות(שם_מקבל, טלפון_מקבל, כתובת_מקבל_ההזמנה, עיר, לקוחות(שם_פרטי, שם_משפחה)),
      שליחים!courier_id(*)
    `)
    .eq('id', deliveryId)
    .single();

  if (fetchErr) {
    console.error('[delivery PATCH] fetch error:', fetchErr.message, '| delivery id:', deliveryId);
    return NextResponse.json({ error: fetchErr.message }, { status: 500 });
  }
  if (!existing) {
    console.error('[delivery PATCH] delivery not found for id:', deliveryId);
    return NextResponse.json({ error: 'משלוח לא נמצא' }, { status: 404 });
  }

  const prevStatus = existing.סטטוס_משלוח;
  console.log('[delivery PATCH] old status:', prevStatus, '→ נאסף');

  // ── Idempotency guard: never re-fire WhatsApp on a no-op transition ────────
  // Two cases this guard covers:
  //   1. The row was already 'נאסף' — caller (button double-click, stray
  //      PATCH from a refresh, etc.) is asking for a transition that's
  //      already happened. Persist any other body fields and exit, no send.
  //   2. whatsapp_sent_at is set on the row — even if a status transition
  //      somehow re-fires (status flipped to ממתין and back), the courier
  //      was already notified. The owner must explicitly resend via a
  //      future "resend WhatsApp" action, not as a side effect of a PATCH.
  const alreadyCollected = prevStatus === 'נאסף';
  const alreadyNotified = !!existing.whatsapp_sent_at;
  if (alreadyCollected || alreadyNotified) {
    console.log('[delivery PATCH] idempotent no-op — alreadyCollected:', alreadyCollected, '| alreadyNotified:', alreadyNotified, '— persisting body without WhatsApp resend');
    const { data, error } = await supabase
      .from('משלוחים')
      .update(body)
      .eq('id', deliveryId)
      .select()
      .single();
    if (error) return NextResponse.json({ error: error.message }, { status: 500 });
    return NextResponse.json({
      data,
      whatsapp_url: null,
      send_error: null,
      was_created: wasCreated,
      // Surface the reason so the frontend can show a quieter toast instead
      // of opening WhatsApp again.
      already_notified: true,
    });
  }

  // 2. Generate token if missing
  let token = existing.delivery_token as string | null;
  if (!token) {
    token = randomBytes(32).toString('hex');
    console.log('[delivery PATCH] generated new token');
  }

  const origin = buildOrigin(req);
  const deliveryLink = `${origin}/delivery-update/${token}`;

  // 3. Resolve recipient name + address + phone (delivery's own address takes precedence over the order's)
  type OrderJoin = {
    שם_מקבל?: string | null;
    טלפון_מקבל?: string | null;
    כתובת_מקבל_ההזמנה?: string | null;
    עיר?: string | null;
    לקוחות?: { שם_פרטי: string; שם_משפחה: string } | null;
  };
  const order = existing.הזמנות as OrderJoin | null;
  const recipientName =
    order?.שם_מקבל ||
    (order?.לקוחות ? `${order.לקוחות.שם_פרטי} ${order.לקוחות.שם_משפחה}` : '') ||
    'לקוח';
  const deliveryRow = existing as { כתובת?: string | null; עיר?: string | null };
  const addrStreet = deliveryRow.כתובת || order?.כתובת_מקבל_ההזמנה || null;
  const addrCity   = deliveryRow.עיר   || order?.עיר                  || null;
  const fullAddress = [addrStreet, addrCity].filter(Boolean).join(', ') || null;
  const recipientPhone = order?.טלפון_מקבל || null;

  // 4. Build update payload
  const updatePayload: Record<string, unknown> = {
    ...body,
    delivery_token: token,
  };

  // 5. Determine send channel
  // Auto-email is intentionally OFF — email is manual only via /send-courier-email.
  type CourierRow = { שם_שליח: string; טלפון_שליח?: string | null; אימייל_שליח?: string | null } | null;
  const courier = existing.שליחים as CourierRow;

  let whatsappUrl: string | null = null;
  let sendError: string | null = null;

  // Control-center kill-switch for courier notifications. The status flip
  // itself still happens (admin might pause WhatsApp temporarily for testing
  // but still want to record that a delivery was picked up). Skipped runs
  // are logged so the operator can see exactly which dispatches went silent.
  const notificationsEnabled = await isServiceEnabled(supabase, 'delivery_notifications');

  if (!courier) {
    console.log('[delivery PATCH] no courier assigned — skip auto-send');
  } else if (!notificationsEnabled) {
    console.log('[delivery PATCH] delivery_notifications is OFF in control center — courier NOT messaged');
    sendError = 'שירות שליחת קישור לשליח כבוי במרכז הבקרה';
    await logServiceRun(supabase, {
      serviceKey:  'delivery_notifications',
      action:      'send_courier_link',
      status:      'disabled',
      relatedType: 'delivery',
      relatedId:   deliveryId,
      message:     `WhatsApp NOT sent to ${courier.שם_שליח}`,
    });
  } else if (courier.טלפון_שליח) {
    // Always rebuild the URL on every status→נאסף transition. The "don't reopen
    // on refresh" semantics is enforced on the frontend (only fires inside the
    // PATCH callback of a real status change). whatsapp_sent_at is informational.
    whatsappUrl = buildWaUrl(
      courier.טלפון_שליח,
      courier.שם_שליח,
      recipientName,
      fullAddress,
      recipientPhone,
      deliveryLink,
    );
    updatePayload.whatsapp_sent_at = new Date().toISOString();
    console.log('[delivery PATCH] WhatsApp URL built for courier:', courier.שם_שליח);
    await logServiceRun(supabase, {
      serviceKey:  'delivery_notifications',
      action:      'send_courier_link',
      status:      'success',
      relatedType: 'delivery',
      relatedId:   deliveryId,
      message:     `WhatsApp link generated for ${courier.שם_שליח}`,
    });
  } else {
    sendError = 'חסר טלפון לשליח';
    console.warn('[delivery PATCH] courier has no phone:', courier.שם_שליח);
  }

  // 6. Persist update
  const { data, error: updateErr } = await supabase
    .from('משלוחים')
    .update(updatePayload)
    .eq('id', deliveryId)
    .select()
    .single();

  if (updateErr) {
    console.error('[delivery PATCH] update failed:', updateErr.message);
    return NextResponse.json({ error: updateErr.message }, { status: 500 });
  }

  console.log('[delivery PATCH] update saved | whatsapp_url:', !!whatsappUrl, '| send_error:', sendError);

  // Activity log: status flip + (separate) courier-link send.
  if (prevStatus !== 'נאסף') {
    void logActivity({
      actor:       userActor(auth),
      module:      'deliveries',
      action:      'delivery_status_changed',
      status:      'success',
      entityType:  'delivery',
      entityId:    deliveryId,
      title:       `שינוי סטטוס משלוח: ${prevStatus ?? '—'} → נאסף`,
      oldValue:    { סטטוס_משלוח: prevStatus },
      newValue:    { סטטוס_משלוח: 'נאסף' },
      request:     req,
    });
  }
  if (whatsappUrl) {
    void logActivity({
      actor:       userActor(auth),
      module:      'deliveries',
      action:      'courier_link_sent',
      status:      'success',
      entityType:  'delivery',
      entityId:    deliveryId,
      entityLabel: courier?.שם_שליח || null,
      title:       'נשלח קישור לשליח',
      description: courier ? `שליח: ${courier.שם_שליח}` : null,
      serviceKey:  'delivery_notifications',
      request:     req,
    });
  } else if (sendError) {
    void logActivity({
      actor:       userActor(auth),
      module:      'deliveries',
      action:      'courier_link_failed',
      status:      sendError.includes('כבוי') ? 'disabled' : 'failed',
      entityType:  'delivery',
      entityId:    deliveryId,
      entityLabel: courier?.שם_שליח || null,
      title:       'שליחת קישור לשליח לא בוצעה',
      errorMessage: sendError,
      serviceKey:  'delivery_notifications',
      request:     req,
    });
  }

  return NextResponse.json({
    data,
    token,
    delivery_link: deliveryLink,
    whatsapp_url: whatsappUrl,
    send_error: sendError,
    was_created: wasCreated,
  });
}

// ─── DELETE ───────────────────────────────────────────────────────────────────
// Removes a delivery row only. Never touches:
//   - הזמנות (the linked order stays exactly as it was)
//   - לקוחות (customer untouched)
//   - חשבוניות (invoices/receipts untouched)
//   - תנועות_מלאי (inventory ledger untouched)
//
// After delete, the public /delivery-update/[token] route automatically
// returns a not-found / friendly message (the row is gone, the token GET
// returns 404 and the page renders the "המשלוח לא נמצא או שכבר אינו פעיל"
// state — no extra invalidation step required).
//
// Auth: same gate as PATCH (requireManagementUser). Public callers cannot
// hit this — the public token route only supports GET / POST(נמסר).
//
// Synthetic ids (no-record-{orderId}) are rejected: there's no DB row to
// delete; the dashboard should drop them from local state without calling
// this endpoint at all.
export async function DELETE(req: NextRequest, { params }: { params: { id: string } }) {
  const auth = await requireManagementUser();
  if (!auth) return unauthorizedResponse();

  if (!params.id || params.id.startsWith('no-record-')) {
    console.warn('[delivery DELETE] refused — synthetic / missing id:', params.id);
    return NextResponse.json(
      { error: 'אין רשומת משלוח למחיקה.' },
      { status: 400 },
    );
  }

  const supabase = createAdminClient();

  // Look up first so we can return a useful response (and a clear log) if
  // the row was already deleted or never existed.
  const { data: existing, error: fetchErr } = await supabase
    .from('משלוחים')
    .select('id, סטטוס_משלוח, הזמנה_id')
    .eq('id', params.id)
    .maybeSingle();

  if (fetchErr) {
    console.error('[delivery DELETE] fetch failed:', fetchErr.message);
    return NextResponse.json({ error: fetchErr.message }, { status: 500 });
  }
  if (!existing) {
    return NextResponse.json({ error: 'המשלוח לא נמצא' }, { status: 404 });
  }

  console.log('[delivery DELETE] deleting delivery row',
    '| id:', existing.id,
    '| order id (kept untouched):', existing.הזמנה_id,
    '| status was:', existing.סטטוס_משלוח);

  const { error: deleteErr } = await supabase
    .from('משלוחים')
    .delete()
    .eq('id', params.id);

  if (deleteErr) {
    console.error('[delivery DELETE] delete failed:', deleteErr.message);
    // Surface FK / constraint failures verbatim so the operator (and a future
    // reader of the logs) can see exactly what blocked the delete. Owner
    // policy: do not run a migration to relax a constraint without approval.
    const isFK = deleteErr.message.includes('foreign key') || deleteErr.message.includes('violates');
    return NextResponse.json(
      { error: isFK
        ? 'לא ניתן למחוק — קיים קישור פעיל למשלוח. ייתכן שצריך migration.'
        : `לא ניתן למחוק את המשלוח: ${deleteErr.message}` },
      { status: isFK ? 409 : 500 },
    );
  }

  void logActivity({
    actor:       userActor(auth),
    module:      'deliveries',
    action:      'delivery_deleted',
    status:      'success',
    entityType:  'delivery',
    entityId:    params.id,
    title:       'משלוח נמחק',
    description: `הזמנה: ${existing.הזמנה_id}`,
    metadata:    { previous_status: existing.סטטוס_משלוח },
    request:     req,
  });

  return NextResponse.json({ ok: true, deleted_id: params.id });
}
